first version of hw
eryzhkova/ibs-html-css-practice pull request #1
Opened 2021-06-03 18:56 UTC by eryzhkova

2021-06-04 00:26 UTC, Roman-Maksimov requested changes

2021-06-04 00:26 UTC, Roman-Maksimov commented on index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
В данном случае не принципиальной разницы нет, но рекомендую всегда помещать вашу таблицу стилей последней. Так у вас будет возможность переопределять third-party стили.

2021-06-04 00:26 UTC, Roman-Maksimov commented on index.html
> +                <img src="google-home-voice-command-device-amazon-echo-google-assistant-voice-command-device-d33abfc7403668afbd14357605a38f6c.png" alt="Device picture" />
Хорошо бы саму картинку тоже закомитить, для наглядности

2021-06-04 00:26 UTC, Roman-Maksimov commented on styles.css
> +input#search {
В верстке лучше избегать ID. Селекторы type тоже, по возможности лучше не использовать. Большинство селекторов - классы.

2021-06-04 00:26 UTC, Roman-Maksimov commented on styles.css
> +}
Обратите внимание на длину поля. По макету оно должно быть 300px на Desktop-е и 200px на мобильном варианте

2021-06-04 00:26 UTC, Roman-Maksimov commented on styles.css
> +    transition: border-bottom-color .2s linear;
иконку тоже бы анимировать

2021-06-04 00:26 UTC, Roman-Maksimov commented on styles.css
> +}
Когда будете натягивать верстку на данные, скорее всего вы не будете знать точный размер картинки. Тут требуется что-то более относительное

2021-06-04 00:26 UTC, Roman-Maksimov commented on styles.css
> +    border: 1px solid rgba(1, 1, 1, 1);
Нет смысла использовать функцию, тем более с альфа-каналом (4-ый аргумент говорит о том, что в используете прозрачность). К тому же, по макету тут должен быть цвет `#323232`

2021-06-04 00:26 UTC, Roman-Maksimov commented on styles.css
> +}
Анимация здесь не помешает

2021-06-04 00:26 UTC, Roman-Maksimov commented on styles.css
> +@media (max-width: 457px) {
457px для каталога вроде подходит, но для детальной страницы - нет. При ширине окна около 500px появляется горизонтальной скрол, его быть не должно.
PS не обязательно делать один media. Можно сделать разные, один для каталога, другой для детальной страницы.

2021-06-04 05:01 UTC, eryzhkova commented on styles.css
> +@media (max-width: 457px) {
Исправлено, готово к проверке!

2021-06-04 15:15 UTC, Roman-Maksimov requested changes

2021-06-04 15:15 UTC, Roman-Maksimov commented on styles.css
> +    transition: fill .2s linear;
у вас два `transition` в одном стиле. Последний может переопределить первый (зависит от браузера). Лучше их разнести по разным стилям.

2021-06-04 15:15 UTC, Roman-Maksimov commented on styles.css
> +    transition: fill .2s linear;
transition прописан для псевдоклассов. Это значит, что формально, браузер обязан анимировать только переход `:focus -> :not(:focus)`, а обратно - не обязан. Хотя некоторые браузеры  и умеют это разруливать, transition лучше прописывать для основного стиля (если только вы не хотите принудительно анимировать только в одну сторону)

2021-06-04 15:15 UTC, Roman-Maksimov commented on styles.css
> +}
Аналогично, рекомендую прописывать transition в основном классе

2021-06-04 15:26 UTC, eryzhkova commented on styles.css
> +    transition: fill .2s linear;
Я могу убрать первый transition на рамку в основной стиль для input и svg, но на fill не смогу убрать, так как опять получится два в одном стиле (для svg). Оставить или просто убрать анимацию?

2021-06-08 11:31 UTC, Roman-Maksimov requested changes

2021-06-08 11:31 UTC, Roman-Maksimov commented on styles.css
> +    transition: fill .2s linear;
в псевдоклассах вообще не стоит прописывать transition (кроме случаев, когда это действительно требуется по верстке). Дело в том, что формально, такой transition появится только в тот момент, когда псевдокласс будет активирован. В современных браузерах, это не проблема, но в некоторых старых версиях такой transition просто не сработает в момент активации псевдокласса, только в момент деактивации.
В вашем случае `transition: fill` стоит перенести в основной класс `.svg-item-icon`. Так вы решаете сразу два вопроса, переопределение transition и переход в псевдокласс.
Если вас смущает уже имеющийся в основном классе `transition: border-bottom-color`, это легко решается одним из двух способов:

```css
  /* вариант 1 */
  transition: all .2s linear; /* будет срабатывать на переход любого свойства */

  /* вариант 2 */
  transition-property: border-bottom-color, fill; /* устанавливает переход для произвольного кол-ва свойств */
  transition-duration: .2s; /* это и следующее свойство тоже могут принимать несколько значений одновременно. Каждое значение будет применено к соответствующему свойству transition-property */
  transition-timing-function: linear;
```

2021-06-08 15:49 UTC, Roman-Maksimov approved these changes

2021-06-08 17:08 UTC, merged